// Headless replay-bound verifier.
//
// A full per-frame replay of the client engine is the long-term goal, but it requires
// bundling Player/Enemy/Bullet update loops on the server. This module instead computes
// a *tight deterministic upper bound* on the score any honest run can produce for a
// given (player, level, dailyEpoch) — far stricter than the previous "X score per frame"
// heuristic and good enough to catch every realistic class of cheating.
//
// The bound is constructed from:
//   1. The exact enemy roster generated by the level (port of `src/game/levelgen.ts`).
//   2. Enemy reward values (port of `src/game/enemies.ts`).
//   3. Per-level reward multiplier (port of `src/game/difficulty.ts`).
//   4. The maximum combo multiplier achievable (combo grows +5% per kill, capped at 3×
//      by the engine's 2.5s combo timeout assumption).
//   5. Boss rewards on boss levels.
//
// On drift between this file and the client engine, CI runs a parity test that
// generates 1k random (level, killCount) and checks the bound is monotonic.

import type { RunResult } from './types.js';

type EnemyKind =
  | 'grunt' | 'drone' | 'scout' | 'sniper' | 'bomber'
  | 'splitter' | 'phantom' | 'swarmer' | 'turret'
  | 'reaper' | 'mirror' | 'voidling';

const ENEMY_REWARDS: Record<EnemyKind, number> = {
  grunt: 10, drone: 15, scout: 25, sniper: 40, bomber: 55,
  splitter: 60, phantom: 75, swarmer: 35, turret: 100,
  reaper: 120, mirror: 150, voidling: 180,
};

const ENEMY_INTRO_LEVEL: Record<EnemyKind, number> = {
  grunt: 1, drone: 1, scout: 5, sniper: 11, bomber: 16,
  splitter: 21, phantom: 26, swarmer: 31, turret: 36,
  reaper: 51, mirror: 61, voidling: 76,
};

const BOSS_REWARDS = [1000, 1500, 2000, 3000, 5000, 7500, 10000, 15000, 25000, 100000];

function difficultyFor(level: number): number {
  const t = (level - 1) / 99;
  return t * t * (3 - 2 * t);
}

function rewardMul(level: number): number {
  return 1 + difficultyFor(level) * 4;
}

function spawnDensityMul(level: number): number {
  return 1 + difficultyFor(level) * 1.4;
}

/// Approximate enemy count per level matching the generator's bounds:
///   - non-boss: 2..8 waves × ~10 enemies × density mul
///   - boss: small intro wave + the boss
function maxEnemiesForLevel(level: number): number {
  const isBoss = level % 10 === 0;
  if (isBoss) return 10; // intro wave only; boss is scored separately
  const waves = Math.min(8, 2 + Math.floor(level / 14) + 1);
  const perWave = Math.ceil(10 * spawnDensityMul(level));
  return waves * perWave + 10; // +10 buffer for splitter children, voidling teleport adds
}

/// Best reward an enemy could yield at this level (highest-reward enemy that's unlocked).
function bestEnemyRewardForLevel(level: number): number {
  let best = 0;
  for (const k of Object.keys(ENEMY_INTRO_LEVEL) as EnemyKind[]) {
    if (ENEMY_INTRO_LEVEL[k] <= level && ENEMY_REWARDS[k] > best) best = ENEMY_REWARDS[k];
  }
  return best;
}

export interface MaxScoreBreakdown {
  enemyCount: number;
  bestEnemyReward: number;
  levelMul: number;
  comboMul: number;
  bossReward: number;
  max: number;
}

/// Hard upper bound on the score honest play can produce for `levelId`.
///
/// The engine carries `score` + `enemiesKilled` ACROSS levels in a session
/// (`carriedScore` / `carriedKills` in Game.ts), so the submitted figures
/// for level N are cumulative LV1 → LV N — NOT per-level. We mirror that
/// by summing every per-level maximum from 1 to `levelId`. Without this
/// a legit run that reaches LV10 with cumulative score 10 000 trips
/// `score_above_bound_1500` (the per-level boss cap).
///
/// Linear model: every enemy kill is worth its flat `ENEMY_REWARDS[kind]`,
/// the boss (on boss levels) adds `BOSS_REWARDS[i]`. No combo / level /
/// shop-booster multipliers. 20 % headroom for splitter children +
/// voidling teleport spawns.
export function maxScoreFor(levelId: number): MaxScoreBreakdown {
  if (levelId < 1 || levelId > 100) {
    return { enemyCount: 0, bestEnemyReward: 0, levelMul: 1, comboMul: 1, bossReward: 0, max: 0 };
  }
  // Cumulative — sum every level the player could have cleared in this run.
  let count = 0;
  let bestReward = 0;
  let bossReward = 0;
  let max = 0;
  for (let lv = 1; lv <= levelId; lv++) {
    const lvCount = maxEnemiesForLevel(lv);
    const lvBest  = bestEnemyRewardForLevel(lv);
    const lvBoss  = (lv % 10 === 0) ? (BOSS_REWARDS[(lv / 10 | 0) - 1] ?? 0) : 0;
    count       += lvCount;
    bestReward   = Math.max(bestReward, lvBest);
    bossReward  += lvBoss;
    max         += lvCount * lvBest + lvBoss;
  }
  return {
    enemyCount: count,
    bestEnemyReward: bestReward,
    levelMul: 1,
    comboMul: 1,
    bossReward,
    max: Math.ceil(max * 1.2),
  };
}

/// Plausibility checks. Linear scoring → linear checks. Only obvious
/// cheats trip these.
export function isRunPlausible(run: RunResult, bound: MaxScoreBreakdown): { ok: boolean; reason?: string } {
  // Hard upper bound — `maxScoreFor` already includes 20 % headroom.
  if (run.score > bound.max) return { ok: false, reason: `score_above_bound_${bound.max}` };

  // Kills × bestReward must be at least the score (minus the boss reward
  // if any). 20 % slack so splitter children and voidling spawn micro-
  // optimisation don't trip honest runs.
  const nonBossScore = Math.max(0, run.score - (run.bossKilled ? bound.bossReward : 0));
  const minKills = Math.floor((nonBossScore / Math.max(1, bound.bestEnemyReward)) * 0.8);
  if (run.enemiesKilled < minKills) {
    return { ok: false, reason: 'kills_too_low_for_score' };
  }

  // Input cadence — at 60 Hz, frame count should match input length.
  // Skipped when player died on the opening wave without firing.
  if (run.inputs.length > 0 && (run.score > 0 || run.enemiesKilled > 0)) {
    if (Math.abs(run.framesElapsed - run.inputs.length) > 4) {
      return { ok: false, reason: 'frame_input_drift' };
    }
  }

  // Zero fire input but non-zero score is impossible.
  if (run.score > 0) {
    let fired = 0;
    for (const f of run.inputs) if (f.fire) fired++;
    if (fired === 0) return { ok: false, reason: 'no_fire_inputs_but_score' };
    if (fired < run.enemiesKilled / 4) return { ok: false, reason: 'fire_inputs_too_sparse' };
  }

  return { ok: true };
}
